In [10]:
import numpy as np
import timeit
from scipy.linalg import svd, qr
A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]])
print(A)

[[ 1 -2  3 -3]
 [ 2 -4  9 -2]
 [-3  6 -9  9]]


In [11]:
# Task - 1

In [12]:
# Using QR Factorization
Q, R = qr(A)
basis_qr = Q
print("Basis for Column Space using QR Factorization:")
print(basis_qr)

Basis for Column Space using QR Factorization:
[[-0.26726124  0.95618289 -0.11952286]
 [-0.53452248 -0.04390192  0.84401323]
 [ 0.80178373  0.28945968  0.52283453]]


In [13]:
# Using SVD
U, S, Vt = svd(A)
basis_svd = U[:, :np.linalg.matrix_rank(A)]
print("\nBasis for Column Space using SVD:")
print(basis_svd)             


Basis for Column Space using SVD:
[[-0.26623586 -0.17064134]
 [-0.5396153   0.84191171]
 [ 0.79870758  0.51192403]]


In [14]:
# Task - 2

In [15]:
#Check if Basis QR can be expressed as a linear combination of Basis SVD
qr_in_svd = all(np.isclose(basis_svd.T @ basis_qr[:, i], 0).all() for i in range(basis_qr.shape[1]))

# Check if Basis SVD can be expressed as a linear combination of Basis QR
svd_in_qr = all(np.isclose(basis_qr.T @ basis_svd[:, i], 0).all() for i in range(basis_svd.shape[1]))

# Print the results
print("Is Basis QR a linear combination of Basis SVD?", qr_in_svd)
print("Is Basis SVD a linear combination of Basis QR?", svd_in_qr)


Is Basis QR a linear combination of Basis SVD? False
Is Basis SVD a linear combination of Basis QR? False


In [16]:
# Task - 3

In [20]:
# Generate a random 500x500 matrix
random_matrix = np.random.rand(500, 500)

# Define the functions for QR and SVD methods
def basis_qr():
    Q, R = qr(random_matrix)
    return Q

def basis_svd():
    U, S, Vt = svd(random_matrix)
    return U[:, :np.linalg.matrix_rank(random_matrix)]

# Measure the execution time for each method
time_qr = timeit.timeit(basis_qr, number=1)
time_svd = timeit.timeit(basis_svd, number=1)

# Print the execution times
print(f"Time taken using QR factorization: {time_qr:.5f} seconds")
print(f"Time taken using SVD: {time_svd:.5f} seconds")

Time taken using QR factorization: 0.01252 seconds
Time taken using SVD: 0.06705 seconds


In [22]:
# Compare the execution times
if time_qr < time_svd:
    conclusion = "QR factorization is faster."
elif time_qr > time_svd:
    conclusion = "SVD is faster."
else:
    conclusion = "QR factorization and SVD have similar execution times."

# Print the conclusion
print(conclusion)

QR factorization is faster.
