In [1]:
import numpy as np
import math

In [2]:
A = [0.1, 1.3, 0.4, 0.5] # list
a = np.array(A) # numpy array
type(a), type(A)

(numpy.ndarray, list)

In [3]:
a.dtype # a's common element type (A.dtype is undefined!)

dtype('float64')

In [4]:
2*a

array([0.2, 2.6, 0.8, 1. ])

In [5]:
2*A

[0.1, 1.3, 0.4, 0.5, 0.1, 1.3, 0.4, 0.5]

In [7]:
n = 100000
x = np.linspace(0, 2*np.pi, n)

In [8]:
# list comprehension
%timeit y = [math.sin(x[i]) * math.exp(-x[i]) for i in range(n)]
# use numpy ufuncs
%timeit y = np.sin(x) * np.exp(-x)

109 ms ± 5.74 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
4.04 ms ± 305 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
def f(v): # apply f to one scalar value v
    return math.sin(v) * math.exp(-v)

In [10]:
vectorizedf = map(f, x) # apply same f to a vector of values x

In [11]:
F = np.vectorize(f) # F can be applied to a array x

In [12]:
# use map
%timeit y = list(map(f, x))
# use numpy's vectorize
%timeit y = F(x)
# use numpy's ufunc
%timeit y = np.sin(x) * np.exp(-x)

78.7 ms ± 2.24 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
75 ms ± 4.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.55 ms ± 136 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
%timeit for x in range(1000000): x**3
%timeit for x in np.arange(1000000): x**3

256 ms ± 12.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
268 ms ± 7.19 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
a = np.random.randint(0,9,5)
a

array([8, 3, 4, 2, 0])

In [15]:
a[::]

array([8, 3, 4, 2, 0])

In [16]:
a[-3:]

array([4, 2, 0])

In [17]:
a[-1], a[len(a)-1]

(0, 0)

In [18]:
a[-4:-1:2]

array([3, 2])

In [19]:
slice = range(-4,-1,2) # Think of b:e:s specification as a range.
a[-4:-1:2], a[slice] # In older versions, a[slice] may not work
# but will work with slice=arange(-4,-1,2).

(array([3, 2]), array([3, 2]))

In [20]:
a = np.array([1,2,3])
b = np.array([3,4,5,6])

In [21]:
a = b
a[0] = 1
a

array([1, 4, 5, 6])

In [22]:
b

array([1, 4, 5, 6])

In [23]:
a = np.array([1,2,3]) # This is Object1 and "a" is a name for it.
b = np.array([3,4,5,6]) # This is Object2 and "b" is a name for it.

In [24]:
id(a), id(b)

(1922081100432, 1922081101104)

In [25]:
a = b # a is no longer a name for Object1, it is now a name for Object2.

In [26]:
id(a), id(b)

(1922081101104, 1922081101104)

In [27]:
a = np.array([1,2,3]) # Object1
b = np.array([3,4,5,6]) # Object2
a = b.copy() # Copies Object2, and binds a to the copy
a[0] = 2 # Only the copied (new) object is changed

In [28]:
a,b

(array([2, 4, 5, 6]), array([3, 4, 5, 6]))

In [29]:
Amat = [[1,2],
[3,4]]
Amat

[[1, 2], [3, 4]]

In [30]:
amat = np.array(Amat)
amat

array([[1, 2],
       [3, 4]])

In [31]:
type(A), type(a)

(list, numpy.ndarray)

In [32]:
2*Amat

[[1, 2], [3, 4], [1, 2], [3, 4]]

In [33]:
2*amat

array([[2, 4],
       [6, 8]])

In [34]:
amat

array([[1, 2],
       [3, 4]])

In [35]:
amat*amat

array([[ 1,  4],
       [ 9, 16]])

In [36]:
import sys
print(sys.version) # check if you have version >= 3.5 before trying @

3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]


In [37]:
amat @ amat

array([[ 7, 10],
       [15, 22]])

In [38]:
np.dot(amat, amat) # dot(A,B) = matrix A multiplied by matrix B

array([[ 7, 10],
       [15, 22]])

In [39]:
amat.dot(amat)

array([[ 7, 10],
       [15, 22]])

In [40]:
amat**2 # not equal to matrix power !!

array([[ 1,  4],
       [ 9, 16]])

In [41]:
np.linalg.matrix_power(amat, 2)

array([[ 7, 10],
       [15, 22]])

In [42]:
A = np.array([[7, 8, 5, 1], [2, 5, 5, 2], [9, 6, 8, 9]])
A

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [43]:
A[1, :], A[:, 2]

(array([2, 5, 5, 2]), array([5, 5, 8]))

In [54]:
A[:3:2, :3]

array([[7, 8, 5],
       [9, 6, 8]])

In [55]:
M = np.array([[7, 8, 5, 1], [2, 5, 5, 2], [9, 6, 8, 9]])
M

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [56]:
M.reshape(2, 6) # Just a different view of the same data

array([[7, 8, 5, 1, 2, 5],
       [5, 2, 9, 6, 8, 9]])

In [57]:
M.ravel() # The 1D data of M in row-major ordering

array([7, 8, 5, 1, 2, 5, 5, 2, 9, 6, 8, 9])

In [58]:
A = np.array(M, order='F')
A

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [59]:
A.ravel(order='A') # A's internal ordering is Fortran style

array([7, 2, 9, 8, 5, 6, 5, 5, 8, 1, 2, 9])

In [60]:
M.ravel(order='A') # M's internal ordering is default C-style

array([7, 8, 5, 1, 2, 5, 5, 2, 9, 6, 8, 9])

In [61]:
N = np.arange(25).reshape(5,5)
N

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
mask = (N>7) & (N<18)
mask

array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False],
       [False, False, False, False, False]])

In [63]:
N[mask]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [64]:
i, j = np.where(mask) # Returns i and j indices where mask[i,j] is True.
i, j # 1st True value of mask is at i[0],j[0],
# 2nd True value of mask is at i[1],j[1], etc.

(array([1, 1, 2, 2, 2, 2, 2, 3, 3, 3], dtype=int64),
 array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2], dtype=int64))

In [65]:
data = np.random.randint(low=0, high=10, size=30) # 1D array

In [66]:
T2 = np.reshape(data, (6, 5)) # 2D array
T2

array([[2, 8, 3, 7, 1],
       [2, 5, 4, 9, 3],
       [9, 5, 3, 4, 6],
       [1, 9, 4, 3, 1],
       [6, 5, 1, 4, 1],
       [3, 2, 2, 3, 1]])

In [67]:
T3 = np.reshape(data, (2, 3, 5)) # 3D array
T3

array([[[2, 8, 3, 7, 1],
        [2, 5, 4, 9, 3],
        [9, 5, 3, 4, 6]],

       [[1, 9, 4, 3, 1],
        [6, 5, 1, 4, 1],
        [3, 2, 2, 3, 1]]])

In [68]:
print('T3 is a ', T3.ndim, 'dimensional array of shape ', T3.shape)
print('T2 is a ', T2.ndim, 'dimensional array of shape ', T2.shape)
print('data is a ', data.ndim, 'dimensional array of shape ', data.shape)

T3 is a  3 dimensional array of shape  (2, 3, 5)
T2 is a  2 dimensional array of shape  (6, 5)
data is a  1 dimensional array of shape  (30,)
