In [32]:
import numpy as np

In [33]:
def matrix(n, k):
    A = np.zeros((n, n))

    for i in range(n):
        for j in range(max(0, i - k), min(n, i + k + 1)):
            A[i, j] = 1
    return A


n = 6
k = 2
A = matrix(n, k)
print(A)

[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [34]:
def average_matrix(n, k):
    A = matrix(n,k)
    
    for i in range(n):
        row_sum = sum(A[i, :])
        A[i, :] /= row_sum

    return A

n = 20
k = 2
A = average_matrix(n, k)
print(A)


[[0.33333333 0.33333333 0.33333333 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.25       0.25       0.25       0.25       0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.2        0.2        0.2        0.2        0.2        0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.2        0.2        0.2        0.2        0.2
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.2        0.2        0.2        0.2
  0.2        0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0

In [35]:
n=20
k=2

x = np.array([(-1)**j for j in range(n)])
x

array([ 1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
       -1,  1, -1])

In [36]:
result = np.dot(A, x)
print(result)

[ 0.33333333  0.          0.2        -0.2         0.2        -0.2
  0.2        -0.2         0.2        -0.2         0.2        -0.2
  0.2        -0.2         0.2        -0.2         0.2        -0.2
  0.         -0.33333333]


In [37]:
def f(x):
    return x**2 + 2*np.sin(10*x)

In [39]:
n = 1000
k = 100
A = create_averaging_operator(n, k)
x = np.linspace(0,10,n)
result = np.dot(A, f(x))
print(result)

[   69.95479022    69.71107309    69.33929524    68.85381621
    68.2703395     67.60575738    66.87798381    66.10577705
    65.30855389    64.50619727    63.71885919    62.96676101
    62.26999296    61.64831503    61.12096118    60.7064487
    60.42239491    60.28534275    60.31059715    60.51207385
    60.90216204    61.49160237    62.2893814     63.30264364
    64.53662205    65.9945876     67.67781861    69.58558989
    71.71518201    74.0619106     76.61917517    79.37852724
    82.32975695    85.46099724    88.75884467    92.20849566
    95.79389667    99.49790693   103.30247206   107.18880682
   111.13758522   115.12913599   119.1436415    123.16133823
   127.1627166    131.12871833   135.04092922   138.88176554
   142.63465205   146.28419      149.81631324   153.21843111
   156.47955646   159.59041768   162.54355352   165.3333898
   167.95629721   170.41062967   172.69674282   174.81699243
   176.77571287   178.57917568   180.23552882   181.75471708
   183.14838452   184.4297