In [38]:
import numpy as np 

In [39]:
def given_swap_row(i, j, A):
    tmp = A[i, :]
    A[i, :] = A[j, :]  
    A[j, :] = tmp 
    return A   

In [40]:
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

result = given_swap_row(0, 2, A)

print(result)


[[7 8 9]
 [4 5 6]
 [7 8 9]]


In [41]:
# There is a error in the given code.Now we modifiy this code and re write

In [42]:
# METHOD-1 : If we restrict the parameters of the indices i,j of the matrix then modified code will be run.

In [43]:
def modified_1_swap_rows(i, j, A):
    if i < 0 or i >= len(A) or j < 0 or j >=len(A):
        print("Invalid row indices.")
    else:
        tmp = A[i, :].copy()  
        A[i, :] = A[j, :]
        A[j, :] = tmp
    return A


In [44]:
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

result = modified_1_swap_rows(1, 2, A)

print(result)


[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [45]:
# METHOD-2 : If we use in-built function A[[i, j]] = A[[j, i]] then the code will run.

In [46]:
import numpy as np

def modified_2_swap_rows(i, j, A):
    tmp = A[i, :].copy() 
    A[[i, j]] = A[[j, i]]
    return A

In [47]:
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

result = modified_2_swap_rows(0, 1, A)

print(result)

[[4 5 6]
 [1 2 3]
 [7 8 9]]
