In [1]:
import numpy as np

In [2]:
x = np.random.rand(5)

In [3]:
D = np.subtract.outer(x, x)  
print(D)

[[ 0.         -0.45089602 -0.36866101  0.15273073 -0.35186861]
 [ 0.45089602  0.          0.08223501  0.60362675  0.09902741]
 [ 0.36866101 -0.08223501  0.          0.52139174  0.0167924 ]
 [-0.15273073 -0.60362675 -0.52139174  0.         -0.50459934]
 [ 0.35186861 -0.09902741 -0.0167924   0.50459934  0.        ]]


In [4]:
A = np.zeros((5,5))
for i in range(5):
  for j in range (5):
    A[i][j]=x[i]-x[j]

print(A)

[[ 0.         -0.45089602 -0.36866101  0.15273073 -0.35186861]
 [ 0.45089602  0.          0.08223501  0.60362675  0.09902741]
 [ 0.36866101 -0.08223501  0.          0.52139174  0.0167924 ]
 [-0.15273073 -0.60362675 -0.52139174  0.         -0.50459934]
 [ 0.35186861 -0.09902741 -0.0167924   0.50459934  0.        ]]
